#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SageFrame.Core.SageFrame.SessionTracking
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DineshTest")]
	public partial class SessionTrackingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SessionTrackingDataContext() : 
				base(global::SageFrame.SessionTracking.Properties.Settings.Default.SageFrameConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SessionTrackingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SessionTrackingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SessionTrackingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SessionTrackingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SessionTrackerAdd")]
		public int sp_SessionTrackerAdd([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionUserHostAddress", DbType="NVarChar(500)")] string sessionUserHostAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionUserAgent", DbType="NVarChar(500)")] string sessionUserAgent, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionBrowser", DbType="NVarChar(500)")] string sessionBrowser, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionCrawler", DbType="NVarChar(500)")] string sessionCrawler, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionURL", DbType="NVarChar(500)")] string sessionURL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionVisitCount", DbType="Int")] System.Nullable<int> sessionVisitCount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionOriginalReferrer", DbType="NVarChar(500)")] string sessionOriginalReferrer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionOriginalURL", DbType="NVarChar(500)")] string sessionOriginalURL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(256)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sessionUserHostAddress, sessionUserAgent, sessionBrowser, sessionCrawler, sessionURL, sessionVisitCount, sessionOriginalReferrer, sessionOriginalURL, username, portalID);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
