<?xml version="1.0" encoding="utf-8"?>
<Database Name="SageFrame" Class="RolesManagementDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.3.26;Initial Catalog=SageFrame;Persist Security Info=True;User ID=sa" SettingsObjectName="SageFrame.RolesManagement.Properties.Settings" SettingsPropertyName="SageFrameConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_SageFrameRolesList" Method="sp_SageFrameRolesList">
    <ElementType Name="sp_SageFrameRolesListResult">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredRoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PortalRoleAdd" Method="sp_PortalRoleAdd">
    <Parameter Name="PortalRoleID" Parameter="portalRoleID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AddedOn" Parameter="addedOn" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="AddedBy" Parameter="addedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_DeleteRole" Method="sp_DeleteRole">
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_PortalRoleDelete" Method="sp_PortalRoleDelete">
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_PortalRoleList" Method="sp_PortalRoleList">
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsAll" Parameter="isAll" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="sp_PortalRoleListResult">
      <Column Name="PortalRoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleId1" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredRoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_RoleGetByUsername" Method="sp_RoleGetByUsername">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_RoleGetByUsernameResult">
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetRoleIDByRoleName" Method="sp_GetRoleIDByRoleName">
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="VarChar(256)" />
    <ElementType Name="sp_GetRoleIDByRoleNameResult">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredRoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>