<?xml version="1.0" encoding="utf-8"?>
<Database Name="SageFrameWebSite" Class="ProfileManagementDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=BRAINDIGNET;Initial Catalog=SageFrameWebSite;Persist Security Info=True;User ID=sa" SettingsObjectName="SageFrame.ProfileManagement.Properties.Settings" SettingsPropertyName="SageFrameConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_ProfileAdd" Method="sp_ProfileAdd">
    <Parameter Name="ProfileID" Parameter="profileID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="PropertyTypeID" Parameter="propertyTypeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DataType" Parameter="dataType" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="IsRequired" Parameter="isRequired" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AddedOn" Parameter="addedOn" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AddedBy" Parameter="addedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ProfileDeleteByProfileID" Method="sp_ProfileDeleteByProfileID">
    <Parameter Name="ProfileID" Parameter="profileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DeletedBy" Parameter="deletedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ProfileGetByProfileID" Method="sp_ProfileGetByProfileID">
    <Parameter Name="ProfileID" Parameter="profileID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ProfileGetByProfileIDResult">
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PropertyTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataType" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="IsRequired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ProfileList" Method="sp_ProfileList">
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ProfileListResult">
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PropertyTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataType" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="IsRequired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PropertyTypeName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ProfileListActive" Method="sp_ProfileListActive">
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ProfileListActiveResult">
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PropertyTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataType" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="IsRequired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PropertyTypeName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ProfileListActiveWithPropertyName" Method="sp_ProfileListActiveWithPropertyName">
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ProfileListActiveWithPropertyNameResult">
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PropertyTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataType" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="IsRequired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PropertyName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ProfileOrderToDownByProfileID" Method="sp_ProfileOrderToDownByProfileID">
    <Parameter Name="ProfileID" Parameter="profileID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ProfileOrderToUpByProfileID" Method="sp_ProfileOrderToUpByProfileID">
    <Parameter Name="ProfileID" Parameter="profileID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ProfileUpdate" Method="sp_ProfileUpdate">
    <Parameter Name="ProfileID" Parameter="profileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="PropertyTypeID" Parameter="propertyTypeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DataType" Parameter="dataType" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="IsRequired" Parameter="isRequired" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsModified" Parameter="isModified" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UpdatedOn" Parameter="updatedOn" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UpdatedBy" Parameter="updatedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ProfileUpdateDisplayOrderOnly" Method="sp_ProfileUpdateDisplayOrderOnly">
    <Parameter Name="ProfileID" Parameter="profileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DisplayOrder" Parameter="displayOrder" Type="System.Int32" DbType="Int" />
    <Parameter Name="UpdatedOn" Parameter="updatedOn" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UpdatedBy" Parameter="updatedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ProfileValueAdd" Method="sp_ProfileValueAdd">
    <Parameter Name="ProfileValueID" Parameter="profileValueID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ProfileID" Parameter="profileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AddedOn" Parameter="addedOn" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AddedBy" Parameter="addedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ProfileValueDeleteByProfileID" Method="sp_ProfileValueDeleteByProfileID">
    <Parameter Name="ProfileID" Parameter="profileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DeletedBy" Parameter="deletedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ProfileValueDeleteByProfileValueID" Method="sp_ProfileValueDeleteByProfileValueID">
    <Parameter Name="ProfileValueID" Parameter="profileValueID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DeletedBy" Parameter="deletedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ProfileValueGetActiveByProfileID" Method="sp_ProfileValueGetActiveByProfileID">
    <Parameter Name="ProfileID" Parameter="profileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ProfileValueGetActiveByProfileIDResult">
      <Column Name="ProfileValueID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProfileID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ProfileValueGetByProfileID" Method="sp_ProfileValueGetByProfileID">
    <Parameter Name="ProfileID" Parameter="profileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ProfileValueGetByProfileIDResult">
      <Column Name="ProfileValueID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProfileID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ProfileValueGetByProfileValueID" Method="sp_ProfileValueGetByProfileValueID">
    <Parameter Name="ProfileValueID" Parameter="profileValueID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ProfileValueGetByProfileValueIDResult">
      <Column Name="ProfileValueID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProfileID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ProfileValueUpdate" Method="sp_ProfileValueUpdate">
    <Parameter Name="ProfileValueID" Parameter="profileValueID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProfileID" Parameter="profileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsModified" Parameter="isModified" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UpdatedOn" Parameter="updatedOn" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UpdatedBy" Parameter="updatedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_PropertyTypeAdd" Method="sp_PropertyTypeAdd">
    <Parameter Name="PropertyTypeID" Parameter="propertyTypeID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_PropertyTypeGet" Method="sp_PropertyTypeGet">
    <Parameter Name="PropertyTypeID" Parameter="propertyTypeID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_PropertyTypeGetResult">
      <Column Name="PropertyTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PropertyTypeList" Method="sp_PropertyTypeList">
    <ElementType Name="sp_PropertyTypeListResult">
      <Column Name="PropertyTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserProfileActiveListByUsername" Method="sp_UserProfileActiveListByUsername">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_UserProfileActiveListByUsernameResult">
      <Column Name="UserProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserProfileAdd" Method="sp_UserProfileAdd">
    <Parameter Name="UserProfileID" Parameter="userProfileID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="ProfileID" Parameter="profileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AddedOn" Parameter="addedOn" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AddedBy" Parameter="addedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserProfileDeleteByUsername" Method="sp_UserProfileDeleteByUsername">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="DeletedBy" Parameter="deletedBy" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserProfileDeleteByUserProfileID" Method="sp_UserProfileDeleteByUserProfileID">
    <Parameter Name="UserProfileID" Parameter="userProfileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DeletedBy" Parameter="deletedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserProfileGetByUserProfileID" Method="sp_UserProfileGetByUserProfileID">
    <Parameter Name="UserProfileID" Parameter="userProfileID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_UserProfileGetByUserProfileIDResult">
      <Column Name="UserProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserProfileListByPortalID" Method="sp_UserProfileListByPortalID">
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_UserProfileListByPortalIDResult">
      <Column Name="UserProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserProfileUpdate" Method="sp_UserProfileUpdate">
    <Parameter Name="UserProfileID" Parameter="userProfileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="ProfileID" Parameter="profileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsModified" Parameter="isModified" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UpdatedOn" Parameter="updatedOn" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UpdatedBy" Parameter="updatedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserProfileUpdateByProfileID" Method="sp_UserProfileUpdateByProfileID">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="ProfileID" Parameter="profileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsModified" Parameter="isModified" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UpdatedOn" Parameter="updatedOn" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UpdatedBy" Parameter="updatedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ProfileUpdateDisplayOrderAndIsActiveOnly" Method="sp_ProfileUpdateDisplayOrderAndIsActiveOnly">
    <Parameter Name="ProfileID" Parameter="profileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DisplayOrder" Parameter="displayOrder" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UpdatedOn" Parameter="updatedOn" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UpdatedBy" Parameter="updatedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ProfileImageFoldersGet" Method="sp_ProfileImageFoldersGet">
    <Parameter Name="EditUserName" Parameter="editUserName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="ProfileID" Parameter="profileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ProfileImageFoldersGetResult">
      <Column Name="UserProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>