#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SageFrame.Core.SageFrame.Message
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="aspxCommerceDemoNov24")]
	public partial class MessageTokenDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MessageTokenDataContext() : 
				base(global::SageFrame.Core.Properties.Settings.Default.aspxCommerceDemoNov24ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MessageTokenDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MessageTokenDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MessageTokenDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MessageTokenDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetUserEmail")]
		public ISingleResult<sp_GetUserEmailResult> sp_GetUserEmail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(256)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, portalID);
			return ((ISingleResult<sp_GetUserEmailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetUserFirstName")]
		public ISingleResult<sp_GetUserFirstNameResult> sp_GetUserFirstName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(256)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, portalID);
			return ((ISingleResult<sp_GetUserFirstNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetUserLastName")]
		public ISingleResult<sp_GetUserLastNameResult> sp_GetUserLastName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(256)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, portalID);
			return ((ISingleResult<sp_GetUserLastNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetUserActivationCode")]
		public ISingleResult<sp_GetUserActivationCodeResult> sp_GetUserActivationCode([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(256)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, portalID);
			return ((ISingleResult<sp_GetUserActivationCodeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_MessageTemplateTypeTokenListByMessageTemplateType")]
		public ISingleResult<sp_MessageTemplateTypeTokenListByMessageTemplateTypeResult> sp_MessageTemplateTypeTokenListByMessageTemplateType([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MessageTemplateTypeID", DbType="Int")] System.Nullable<int> messageTemplateTypeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), messageTemplateTypeID, portalID);
			return ((ISingleResult<sp_MessageTemplateTypeTokenListByMessageTemplateTypeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetActivationTokenValue")]
		public ISingleResult<sp_GetActivationTokenValueResult> sp_GetActivationTokenValue([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(256)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, portalID);
			return ((ISingleResult<sp_GetActivationTokenValueResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetPasswordRecoveryTokenValue")]
		public ISingleResult<sp_GetPasswordRecoveryTokenValueResult> sp_GetPasswordRecoveryTokenValue([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(256)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, portalID);
			return ((ISingleResult<sp_GetPasswordRecoveryTokenValueResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetActivationSuccessfulTokenValue")]
		public ISingleResult<sp_GetActivationSuccessfulTokenValueResult> sp_GetActivationSuccessfulTokenValue([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(256)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, portalID);
			return ((ISingleResult<sp_GetActivationSuccessfulTokenValueResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetPasswordRecoverySuccessfulTokenValue")]
		public ISingleResult<sp_GetPasswordRecoverySuccessfulTokenValueResult> sp_GetPasswordRecoverySuccessfulTokenValue([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(256)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, portalID);
			return ((ISingleResult<sp_GetPasswordRecoverySuccessfulTokenValueResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_GetUserEmailResult
	{
		
		private string _Email;
		
		public sp_GetUserEmailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(256)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
	}
	
	public partial class sp_GetUserFirstNameResult
	{
		
		private string _FirstName;
		
		public sp_GetUserFirstNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(100)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
	}
	
	public partial class sp_GetUserLastNameResult
	{
		
		private string _LastName;
		
		public sp_GetUserLastNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(100)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
	}
	
	public partial class sp_GetUserActivationCodeResult
	{
		
		private System.Guid _UserId;
		
		public sp_GetUserActivationCodeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
	}
	
	public partial class sp_MessageTemplateTypeTokenListByMessageTemplateTypeResult
	{
		
		private int _MessageTemplateTypeTokenID;
		
		private int _MessageTemplateTypeID;
		
		private int _MessageTokenID;
		
		private string _MessageTokenKey;
		
		private string _MessageTokenName;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<bool> _IsModified;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private System.Nullable<int> _PortalID;
		
		private string _AddedBy;
		
		private string _UpdatedBy;
		
		private string _DeletedBy;
		
		public sp_MessageTemplateTypeTokenListByMessageTemplateTypeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageTemplateTypeTokenID", DbType="Int NOT NULL")]
		public int MessageTemplateTypeTokenID
		{
			get
			{
				return this._MessageTemplateTypeTokenID;
			}
			set
			{
				if ((this._MessageTemplateTypeTokenID != value))
				{
					this._MessageTemplateTypeTokenID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageTemplateTypeID", DbType="Int NOT NULL")]
		public int MessageTemplateTypeID
		{
			get
			{
				return this._MessageTemplateTypeID;
			}
			set
			{
				if ((this._MessageTemplateTypeID != value))
				{
					this._MessageTemplateTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageTokenID", DbType="Int NOT NULL")]
		public int MessageTokenID
		{
			get
			{
				return this._MessageTokenID;
			}
			set
			{
				if ((this._MessageTokenID != value))
				{
					this._MessageTokenID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageTokenKey", DbType="NVarChar(100)")]
		public string MessageTokenKey
		{
			get
			{
				return this._MessageTokenKey;
			}
			set
			{
				if ((this._MessageTokenKey != value))
				{
					this._MessageTokenKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageTokenName", DbType="NVarChar(100)")]
		public string MessageTokenName
		{
			get
			{
				return this._MessageTokenName;
			}
			set
			{
				if ((this._MessageTokenName != value))
				{
					this._MessageTokenName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsModified", DbType="Bit")]
		public System.Nullable<bool> IsModified
		{
			get
			{
				return this._IsModified;
			}
			set
			{
				if ((this._IsModified != value))
				{
					this._IsModified = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this._AddedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this._DeletedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalID", DbType="Int")]
		public System.Nullable<int> PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedBy", DbType="NVarChar(256)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(256)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="NVarChar(256)")]
		public string DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this._DeletedBy = value;
				}
			}
		}
	}
	
	public partial class sp_GetActivationTokenValueResult
	{
		
		private System.Guid @__UserActivationCode_;
		
		private string @__Username_;
		
		private string @__UserFirstName_;
		
		private string @__UserLastName_;
		
		private string @__UserEmail_;
		
		public sp_GetActivationTokenValueResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%UserActivationCode%]", Storage="__UserActivationCode_", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid _UserActivationCode_
		{
			get
			{
				return this.@__UserActivationCode_;
			}
			set
			{
				if ((this.@__UserActivationCode_ != value))
				{
					this.@__UserActivationCode_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%Username%]", Storage="__Username_", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string _Username_
		{
			get
			{
				return this.@__Username_;
			}
			set
			{
				if ((this.@__Username_ != value))
				{
					this.@__Username_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%UserFirstName%]", Storage="__UserFirstName_", DbType="NVarChar(100)")]
		public string _UserFirstName_
		{
			get
			{
				return this.@__UserFirstName_;
			}
			set
			{
				if ((this.@__UserFirstName_ != value))
				{
					this.@__UserFirstName_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%UserLastName%]", Storage="__UserLastName_", DbType="NVarChar(100)")]
		public string _UserLastName_
		{
			get
			{
				return this.@__UserLastName_;
			}
			set
			{
				if ((this.@__UserLastName_ != value))
				{
					this.@__UserLastName_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%UserEmail%]", Storage="__UserEmail_", DbType="NVarChar(256)")]
		public string _UserEmail_
		{
			get
			{
				return this.@__UserEmail_;
			}
			set
			{
				if ((this.@__UserEmail_ != value))
				{
					this.@__UserEmail_ = value;
				}
			}
		}
	}
	
	public partial class sp_GetPasswordRecoveryTokenValueResult
	{
		
		private System.Guid @__UserActivationCode_;
		
		private string @__Username_;
		
		private string @__UserFirstName_;
		
		private string @__UserLastName_;
		
		private string @__UserEmail_;
		
		public sp_GetPasswordRecoveryTokenValueResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%UserActivationCode%]", Storage="__UserActivationCode_", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid _UserActivationCode_
		{
			get
			{
				return this.@__UserActivationCode_;
			}
			set
			{
				if ((this.@__UserActivationCode_ != value))
				{
					this.@__UserActivationCode_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%Username%]", Storage="__Username_", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string _Username_
		{
			get
			{
				return this.@__Username_;
			}
			set
			{
				if ((this.@__Username_ != value))
				{
					this.@__Username_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%UserFirstName%]", Storage="__UserFirstName_", DbType="NVarChar(100)")]
		public string _UserFirstName_
		{
			get
			{
				return this.@__UserFirstName_;
			}
			set
			{
				if ((this.@__UserFirstName_ != value))
				{
					this.@__UserFirstName_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%UserLastName%]", Storage="__UserLastName_", DbType="NVarChar(100)")]
		public string _UserLastName_
		{
			get
			{
				return this.@__UserLastName_;
			}
			set
			{
				if ((this.@__UserLastName_ != value))
				{
					this.@__UserLastName_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%UserEmail%]", Storage="__UserEmail_", DbType="NVarChar(256)")]
		public string _UserEmail_
		{
			get
			{
				return this.@__UserEmail_;
			}
			set
			{
				if ((this.@__UserEmail_ != value))
				{
					this.@__UserEmail_ = value;
				}
			}
		}
	}
	
	public partial class sp_GetActivationSuccessfulTokenValueResult
	{
		
		private System.Guid @__UserActivationCode_;
		
		private string @__Username_;
		
		private string @__UserFirstName_;
		
		private string @__UserLastName_;
		
		private string @__UserEmail_;
		
		public sp_GetActivationSuccessfulTokenValueResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%UserActivationCode%]", Storage="__UserActivationCode_", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid _UserActivationCode_
		{
			get
			{
				return this.@__UserActivationCode_;
			}
			set
			{
				if ((this.@__UserActivationCode_ != value))
				{
					this.@__UserActivationCode_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%Username%]", Storage="__Username_", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string _Username_
		{
			get
			{
				return this.@__Username_;
			}
			set
			{
				if ((this.@__Username_ != value))
				{
					this.@__Username_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%UserFirstName%]", Storage="__UserFirstName_", DbType="NVarChar(100)")]
		public string _UserFirstName_
		{
			get
			{
				return this.@__UserFirstName_;
			}
			set
			{
				if ((this.@__UserFirstName_ != value))
				{
					this.@__UserFirstName_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%UserLastName%]", Storage="__UserLastName_", DbType="NVarChar(100)")]
		public string _UserLastName_
		{
			get
			{
				return this.@__UserLastName_;
			}
			set
			{
				if ((this.@__UserLastName_ != value))
				{
					this.@__UserLastName_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%UserEmail%]", Storage="__UserEmail_", DbType="NVarChar(256)")]
		public string _UserEmail_
		{
			get
			{
				return this.@__UserEmail_;
			}
			set
			{
				if ((this.@__UserEmail_ != value))
				{
					this.@__UserEmail_ = value;
				}
			}
		}
	}
	
	public partial class sp_GetPasswordRecoverySuccessfulTokenValueResult
	{
		
		private System.Guid @__UserActivationCode_;
		
		private string @__Username_;
		
		private string @__UserFirstName_;
		
		private string @__UserLastName_;
		
		private string @__UserEmail_;
		
		public sp_GetPasswordRecoverySuccessfulTokenValueResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%UserActivationCode%]", Storage="__UserActivationCode_", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid _UserActivationCode_
		{
			get
			{
				return this.@__UserActivationCode_;
			}
			set
			{
				if ((this.@__UserActivationCode_ != value))
				{
					this.@__UserActivationCode_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%Username%]", Storage="__Username_", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string _Username_
		{
			get
			{
				return this.@__Username_;
			}
			set
			{
				if ((this.@__Username_ != value))
				{
					this.@__Username_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%UserFirstName%]", Storage="__UserFirstName_", DbType="NVarChar(100)")]
		public string _UserFirstName_
		{
			get
			{
				return this.@__UserFirstName_;
			}
			set
			{
				if ((this.@__UserFirstName_ != value))
				{
					this.@__UserFirstName_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%UserLastName%]", Storage="__UserLastName_", DbType="NVarChar(100)")]
		public string _UserLastName_
		{
			get
			{
				return this.@__UserLastName_;
			}
			set
			{
				if ((this.@__UserLastName_ != value))
				{
					this.@__UserLastName_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[%UserEmail%]", Storage="__UserEmail_", DbType="NVarChar(256)")]
		public string _UserEmail_
		{
			get
			{
				return this.@__UserEmail_;
			}
			set
			{
				if ((this.@__UserEmail_ != value))
				{
					this.@__UserEmail_ = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
